### ISSUE TITLE
Error during soundcard test on rapsberry pi 4B with audioinjector stereo card

### ISSUE THREAD

**Issue by meteorkees** [sberl/supersid#61]
Soundcard is recognized with arecord -L. It is not a USB card but directly on top of the GPIO pins. see:  https://github.com/Audio-Injector/stereo-and-zero

the error during test:
pi@raspberrypi:~/supersid/supersid $ python3 -u find_alsa_devices.py 2>&1
Version 20220104
Config file '../Config/supersid.cfg' read successfully

audio_sampling_rate, Audio, Device, Format, PeriodSize, regression, result[, duration][, peak frequency / generated frequency = frequency ratio]

This is the list of untested devices:
{'default',
 'dmix:CARD=audioinjectorpi,DEV=0',
 'dsnoop:CARD=audioinjectorpi,DEV=0',
 'hw:CARD=audioinjectorpi,DEV=0',
 'jack',
 'null',
 'plughw:CARD=audioinjectorpi,DEV=0',
 'pulse',
 'sysdefault:CARD=audioinjectorpi',
 'usbstream:CARD=audioinjectorpi'}

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'frequency_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "find_alsa_devices.py", line 1082, in <module>
    config.data_path)
  File "find_alsa_devices.py", line 826, in test
    self.test_summary(test_log, regression)
  File "find_alsa_devices.py", line 838, in test_summary
    (df['frequency_ratio'] >= 0.998) &
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/pi/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'frequency_ratio'

Any suggestion to fix or to find the details of this card to fill the supersid config file?

Many thx, Kees.

**Comment by meteorkees** [comment]
I got the same error with the IQaudIO zero sound card from Raspberry. https://datasheets.raspberrypi.com/iqaudio/iqaudio-product-brief.pdf
Is it because it is not an USB sound card?

**Comment by meteorkees** [comment]
I tried with a USB soundcard on the same Pi. Now the test-script find_alsa_devices.py is running as should be.

Why not with GPIO connected soundcards??

**Comment by sberl** [comment]
Fenrog: I'm guessing from the traceback that this has something to do with the way we are using the pandas library.
Could the variable df in test_summary() be empty after df.dropna()?

meteorkees: would you be willing to help us debug the problem as I expect none of us have the hardware you do? If we send you a version of the code with extra debug output can you run it for us?

**Comment by fenrog** [comment]
There seems to be more than one problem in this bug report.

1) Empty dataframe is not gracefully handled.
> Could the variable df in test_summary() be empty after df.dropna()?
This is the case.

2) audioinjectorpi did not see any sucesfull test.
@meteorkees
I assueme it is the Codec Zero described in chapters 9 and 11. Is this correct?
Chapter 11 describes there are four lodable ALSA settings. Two mono and two stereo settings.
Which of these settings did you load?
Could you try the two stereo settings?
isine.py tries to generate a test tone on 2 channels. If only one channel is supported, I'll have to do some adaptations.

**Comment by fenrog** [comment]
@meteorkees 
You may want to test https://github.com/fenrog/supersid/tree/sberl/61
I cannot test this as I do not have your hardware.
The number of channels when generating the test tone is now the same as the numebr of channels captured. (command line option -n/--channels)
This should support devices with mono output and mono input.

I'm interrested in the output of these commands:
`arecord -L` - ALSA pcms
`python3 find_alsa_devices.py -l` - alsaaudio pcms
`arecord -D hw:CARD=audioinjectorpi,DEV=0 --dump-hw-params -d 1 > /dev/null` - hardware capabilities
Be carefull to use `hw:CARD`, do not use `plughw:CARD` for the third command.

**Comment by fenrog** [comment]
@meteorkees
I had to do further updates. In case you alredy pulled https://github.com/fenrog/supersid/tree/sberl/61, you may want tu update it.

**Comment by meteorkees** [comment]
@Steve
ref: meteorkees: would you be willing to help us debug the problem as I
expect none of us have the hardware you do? If we send you a version of the
code with extra debug output can you run it for us?

—

Yes I will. I see that Fenrog also send me some questions. I will start to
reply on these.

Kees.

Op za 22 jan. 2022 om 20:20 schreef Steve Berl ***@***.***>:

**Comment by meteorkees** [comment]
Hi Fenrog,
ref: audioinjectorpi did not see any sucesfull test.
@meteorkees <https://github.com/meteorkees>
I assueme it is the Codec Zero described in chapters 9 and 11. Is this
correct?
Chapter 11 describes there are four lodable ALSA settings. Two mono and two
stereo settings.
Which of these settings did you load?
Could you try the two stereo settings?
isine.py tries to generate a test tone on 2 channels. If only one channel
is supported, I'll have to do some adaptations

I did not load any settings at all for the codec Zero. Good point. I will
add some RCA connectors to it and load the ' stereo'  files.
I will come back with the results.

Kees.

Op za 22 jan. 2022 om 23:21 schreef fenrog ***@***.***>:

**Comment by meteorkees** [comment]
Hi Fenrog,

ref: arecord -L - ALSA pcms

***@***.***:~ $ arecord -L - ALSA pcms
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
sysdefault:CARD=audioinjectorpi
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Default Audio Device
dmix:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct sample mixing device
dsnoop:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct sample snooping device
hw:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct hardware device without any conversions
plughw:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Hardware device with all software conversions
usbstream:CARD=audioinjectorpi
    audioinjector-pi-soundcard
    USB Stream Output

ref : python3 find_alsa_devices.py -l - alsaaudio pcms

***@***.***:~/supersid/supersid $ python3 find_alsa_devices.py -l -
alsaaudio pcms
Version 20220105
usage: find_alsa_devices.py [-h] [-c CFG_FILENAME] [-b] [-n {1,2}] [-l]
                            [-p PERIODSIZE] [-r REGRESSION] [-t TEST_TONE]
                            [-d DEVICE] [-s] [-v]
find_alsa_devices.py: error: unrecognized arguments: - alsaaudio pcms

ref: arecord -D hw:CARD=audioinjectorpi,DEV=0 --dump-hw-params -d 1 >
/dev/null - hardware capabilities

***@***.***:~/supersid/supersid $ arecord -D
hw:CARD=audioinjectorpi,DEV=0 --dump-hw-params -d 1 > /dev/null - hardware
capabilities
Recording WAVE '-' : Unsigned 8 bit, Rate 8000 Hz, Mono
HW Params of device "hw:CARD=audioinjectorpi,DEV=0":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE S24_LE S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: [16 32]
FRAME_BITS: [32 64]
CHANNELS: 2
RATE: [8000 96000]
PERIOD_TIME: (333 8192000]
PERIOD_SIZE: [32 65536]
PERIOD_BYTES: [256 524288]
PERIODS: [2 4096]
BUFFER_TIME: (666 16384000]
BUFFER_SIZE: [64 131072]
BUFFER_BYTES: [256 524288]
TICK_TIME: ALL
--------------------
arecord: set_params:1339: Sample format non available
Available formats:
- S16_LE
- S24_LE
- S32_LE

Kees.




Op zo 23 jan. 2022 om 02:32 schreef fenrog ***@***.***>:

**Comment by meteorkees** [comment]
Hi Fenrog,

Sorry, i need some help with this. My knowledge is not (yet) good enough to
know how to operate with Github as you developers. So what to do to exactly
in my console to update the files you linked me to?
I assume I have to make a new directory for the supersid/tree/sberl/61 you
suggested??

Kees.



Op zo 23 jan. 2022 om 22:02 schreef fenrog ***@***.***>:

**Comment by fenrog** [comment]
My description for the commands was a bit misleading. What I meant as comment has been passed as parameter.
Could you repeat
`python3 find_alsa_devices.py -l`

**Comment by fenrog** [comment]
I personally created the folder `~/fenrog`.

```
cd ~/fenrog
git clone https://github.com/fenrog/supersid.git
cd ~/fenrog/supersid
git pull
git checkout sberl/61
mkdir Data
mkdir outgoing
```
Now you should have the right branch.  Whenever you see `~/supersid` in the installation guide, replace it with `~/fenrog/supersid`. In case you used the virtual environment, you will have to repeat the installation of Python modules, otherwise you can continue with the configuration file. And finally repeat your test.

```
cd ~/fenrog/supersid/supersid
python3 -u find_alsa_devices.py 2>&1
```

**Comment by meteorkees** [comment]
Clear, thx! Now buzzy at work, hope to have time tomorrow to check it out.

Op maandag 24 januari 2022 schreef fenrog ***@***.***>:

**Comment by meteorkees** [comment]
finally got some time to test your script with the audioinjector hooked on
a PI3B+. I will check later on a PI4.
On the pi3 the script starts running but hangs somewhere half way i think:

***@***.***:~/fenrog/supersid/supersid $ python3 -u find_alsa_devices.py
2>&1
Version 20220123
Config file '../Config/supersid.cfg' read successfully
CARD=audioinjectorpi,DEV=0
rates: [8000, 11025, 16000, 22050, 32000, 44100, 48000, 64000, 88200, 96000]
formats: ['S16_LE', 'S24_LE', 'S32_LE']
channels: 2

audio_sampling_rate, Audio, Device, Format, PeriodSize, regression,
channel, result[, duration][, peak frequency / generated frequency =
frequency ratio]
ERROR test tone: <class 'alsaaudio.ALSAAudioError'> Invalid argument
[plughw:CARD=audioinjectorpi,DEV=0]
test tone started 3675 Hz, 'plughw:CARD=audioinjectorpi,DEV=0'
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  1, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  2, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  3, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  4, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  5, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  6, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  7, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  8, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024,  9, 0,
OK, 1.02 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S16_LE , 1024, 10, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
ERROR: format conversion of 'S24_LE' is not implemented
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S24_LE , 1024,  1, 0,
F_NOT_IMPLEMENTED
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  1, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  2, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  3, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  4, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  5, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  6, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  7, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  8, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024,  9, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000
 11025, alsaaudio, sysdefault:CARD=audioinjectorpi, S32_LE , 1024, 10, 0,
OK, 1.03 s, 0 Hz / 3675 Hz = 0.000

Thats it, nor more respons



Op di 25 jan. 2022 om 16:00 schreef Kees Meteor ***@***.***>:

**Comment by meteorkees** [comment]
the other testcmd output:
***@***.***:~/fenrog/supersid/supersid $ arecord -L - ALSA pcms
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
sysdefault:CARD=audioinjectorpi
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Default Audio Device
dmix:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct sample mixing device
dsnoop:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct sample snooping device
hw:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Direct hardware device without any conversions
plughw:CARD=audioinjectorpi,DEV=0
    audioinjector-pi-soundcard, AudioInjector audio wm8731-hifi-0
    Hardware device with all software conversions
usbstream:CARD=audioinjectorpi
    audioinjector-pi-soundcard
    USB Stream Output
######################################################################

***@***.***:~/fenrog/supersid/supersid $ python3 find_alsa_devices.py -l
- alsaaudio pcms
Version 20220123
usage: find_alsa_devices.py [-h] [-c CFG_FILENAME] [-b] [-n {1,2}] [-l]
                            [-p PERIODSIZE] [-r REGRESSION] [-t TEST_TONE]
                            [-d DEVICE] [-s] [-v]
find_alsa_devices.py: error: unrecognized arguments: - alsaaudio pcms

#######################################################################


***@***.***:~/fenrog/supersid/supersid $ arecord -D
hw:CARD=audioinjectorpi,DEV=0 --dump-hw-params -d 1 > /dev/null - hardware
capabilities
Recording WAVE '-' : Unsigned 8 bit, Rate 8000 Hz, Mono
HW Params of device "hw:CARD=audioinjectorpi,DEV=0":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE S24_LE S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: [16 32]
FRAME_BITS: [32 64]
CHANNELS: 2
RATE: [8000 96000]
PERIOD_TIME: (333 8192000]
PERIOD_SIZE: [32 65536]
PERIOD_BYTES: [256 524288]
PERIODS: [2 4096]
BUFFER_TIME: (666 16384000]
BUFFER_SIZE: [64 131072]
BUFFER_BYTES: [256 524288]
TICK_TIME: ALL
--------------------
arecord: set_params:1339: Sample format non available
Available formats:
- S16_LE
- S24_LE
- S32_LE

######################################################################



Op zo 30 jan. 2022 om 14:11 schreef Kees Meteor ***@***.***>:

**Comment by fenrog** [comment]
This one is critical for the function. It appears as if test tone generation is not working:
```
ERROR test tone: <class 'alsaaudio.ALSAAudioError'> Invalid argument
[plughw:CARD=audioinjectorpi,DEV=0]
```

No more response after a while is also not nice.

Today I ordered an "IQaudio Codec Zero". Let's see whether I can find a solution when I have the device on my desk.

**Comment by meteorkees** [comment]
That would be great, thx. I have also a IQaudio Zero, so let me know if i
can help with some testing.
you can also mail to meteorkees at gmail dot com
Kees

Op di 1 feb. 2022 om 22:01 schreef fenrog ***@***.***>:

**Comment by fenrog** [comment]
Sorry for the long time without an answer. Finally I got the combination of a Raspberry Pi Zero WH + IQaudio Codec Zero working - with the current version of SuperSID without any modification. I followed these main steps:

1. fresh installation of Raspbian OS on the Pi Zero
2. configuration of the sound card according to https://www.elektormagazine.com/news/iqaudio-codec-zero
   In the context menue of the speaker symbol I selected
   Audio Outputs: IQaudIOCODEC
   Audio Inputs: IQaudIOCODEC
   Device Profiles: HDMI: Off; IQaudIOCODEC: Stereo Output + Stereo Input
3. modification of /boot/config.txt according to https://datasheets.raspberrypi.com/iqaudio/iqaudio-product-brief.pdf
   #dtparam=audio=on
   # Enable IQaudo Codec Zero
   dtoverlay=iqaudio-codec
4. setting all gains of the soundcard to about 50% with alsamixer (caution, there are a lot more rulers when scrolling right)
5. fresh installation of SuperSID (sberl current version)

find_alsa_devices.py found some working configurations of which I'd go for
[PARAMETERS]
audio_sampling_rate = 96000
[Capture]
Audio = alsaaudio
Device = hw:CARD=IQaudIOCODEC,DEV=0
Format = S32_LE
Periodsize = 1024
Channels = 2

Although it is a two channels configuration you can still decide to connect the antenna signal to just one of the two channels and to capture the stations with just one channel. In this case I'd recommend to use the left channel of the AUX IN 4 pin header.

Is this ok? Can we close the issue?

**Comment by meteorkees** [comment]
Hello,
thx for the update, and work around. Not yet clear to me if the cmd
find_alsa_devices.py was working properly with the IQaudio Codec Zero?
I will test it this asap and will return the results.



Op zo 6 mrt. 2022 om 21:17 schreef fenrog ***@***.***>:

**Comment by fenrog** [comment]
@meteorkees:
Yes, `python3 -u find_alsa_devices.py 2>&1` was working properly. The proposed configuration has been checked with `supersid.py`.

But before it took me quite a while until I had the card configured in a way that the ALSA stack could work with it. In the first attempts even when folowing guides literally, I got error messages from `arecord`, `aplay`, `speaker-test`. Later when these vanished, I still could not get any signal on the output. I measured with an osciloscope of a friend to see what's generated. At some stage I got an output but instead of the expected sine it was a trapezoid. The gain was too high and the trapezoid was the effect of clipping. Reducing the gain to about 50% on all rulers has had positive effect and the sine was a sine. AT this stage I connected AUX OUT with AUX IN 1:1 and started find_alsa_devices.py and it worked.

find_alsa_devices.py depends on pyalsaaudio and pyalsaaudio depends on the ALSA stack. Search google for `alsa "infinite loop"` and you'll find some scenarios in which ALSA was stuck in an infinte loop. In this case the layers above are stuck as well. The result is a non-responding software.

Handling the empty result list gracefully should be done in order to avoid the traceback reported in your first post.

**Comment by meteorkees** [comment]
Thx for your reply,
I am now updating the Pizero with a IQaudIO zero on top. It takes a
while............ on the Zero...
Tomorrow I will continue the test and report back the results.



Op di 8 mrt. 2022 om 07:02 schreef fenrog ***@***.***>:

**Comment by meteorkees** [comment]
Good evening,
done the first test with the Pi Zero.
Followed all instructions from fenrog (01-03-22).
Script find_alsa_devices.py is running now till the end, but returns no
suitable device was found.

My first run was with a monitor connected to the Pi Zero via HDMI.
Results: no suitable device found.

The second run I disconnected the monitor, reboot the Pi zero, and made a
headless connection via VNC.
result: again: no suitable device found.

In alsamixer I see the IQaudIO card, and I changed as well the settings in
the boot/config.txt file.
I connected the left output channel with the left input channel.

The only thing I suspect is the HDMI setting. I saw in the mail that HDMI
should be off. I can not find where to switch of HDMI. Is this done in in
the boot/config.txt file?



Op di 8 mrt. 2022 om 21:23 schreef Kees Meteor ***@***.***>:

**Comment by meteorkees** [comment]
correction: mail fenrog 06-03-22.

Op wo 9 mrt. 2022 om 20:04 schreef Kees Meteor ***@***.***>:

**Comment by fenrog** [comment]
Did you follow the four steps given in my previous answer?
Number 2) links to the corresponding description https://www.elektormagazine.com/news/iqaudio-codec-zero
Figure 4 illustrates it. Richt clik the speaker symbol and then go through each option of the context menue as described in my previous post.

I also followed this advice, not knowing whether it was relevant for the success or not https://www.elektormagazine.com/news/iqaudio-codec-zero#:~:text=However%2C%20the%20speaker,from%20the%20speaker.

You really need to make sure to get sound on left and right channel of AUX OUT. Connect a speaker, measure, whatever you prefer. As long as there is no singal, there is no point in continuing with find_alsa_devices.py.

Once you get sound on the left and right channel, connect AUX OUT with AUX IN with a 1:1 connection. I soldered two four pin heads to the four through-holes on each side of the PCB and connectet these with a flat wire that I recycled from an old PC. The cable looks similar to these: https://www.amazon.de/-/en/DealMux-24AWG-Female-Ribbon-Cable/dp/B01EZQEDOI.

Only then (sound available on left and right channel and connection made from AUX OUT to AUX IN) find_alsa_devices.py has a chance to actually figure out the best settings.

**Comment by meteorkees** [comment]
Hi Fenrog,
I am now quite busy at work. Next week I will repeat all mentioned steps
again and return the results.
Meanwhile I face often a ‘memory’ on the pi3 with a Xonar U5 soundcard. I
will post a issue on that on GitHub.

Regards, Kees.

Op di 15 mrt. 2022 om 07:57 schreef fenrog ***@***.***>:

**Comment by fenrog** [comment]
According to Asus, Xonar U5 only supports Windows.

1) https://www.amazon.de/ask/questions/asin/B00MI8IDRE/2

In the search filed type linux and then enter.
Q: Does ir works on Linux (Ubuntu)?
A: Dear customer,

Thank you for your question about our product.

The Xonar U5 only supports Windows.

Windows 10 (32/64 Bit)
Windows 8.1 (32/64 Bit)
Windows 7 (32/64 Bit)

We hope that we could help you with our answer.

Yours sincerely,
 
ASUS customer service

2) https://www.asus.com/Motherboards-Components/Sound-Cards/Hi-Fi/Xonar_U5/techspec/

The same is statet here.

**Comment by meteorkees** [comment]
Ref the Xonar soundcard; I used this one because the people from the AAVSO
are pleased with it.
Which soundcard would you recommend to use on a Rpi3 to sample at least 96k?

Op wo 23 mrt. 2022 om 20:13 schreef fenrog ***@***.***>:

**Comment by fenrog** [comment]
I can't and I won't recommend a specific card. In the past I spend a lot of time in the hope to get a sound card working for another participant. He ordered the same sound card I'm using. It can sample up to 192 k samples/second. Unfortunatelly although it was the same device, it anounced itself with different information at the USB bus (different firmware revision and other details). He exchanged the card and again it anounced itself different to mine. We contacted the support of the manufacturer and provided a lot of information to them - without getting any usefull suggestion from the manufacturer (usefull in the sense to get the device working). I ordered a second device of the same type. It worked for me. He ordered a different device of the same brand. It didn't work. So overall after spending a lot of time and money we were at the point that two of my two cards were working and three of three cards of  the other participant were not working and the manufacturer stopped communication.

I did my best to get the scripts working with all soundcards I'm in posession of (PCI and USB sound cards), using different HW, ARM and Intel architecture, 32 and 64 bit, Windows, different (but related) Linux distributions. That's all I can do. Don't forget: I'm a volunteer. I spend my private money and my spare time. Both is limited.

When AAVSO recommends the Xonar U5, they possibly have a guide how to get it working.

**Comment by meteorkees** [comment]
Hello,
it took a while to find some time to pick up Supersid again. 
This time I started fresh with a Pi3B+ with Bullseye and the Audioinjector 'stereo'  soundcard on top of the GPIO pins.
 I installed Suppersid, and then followed the steps from Audioinjector to install the drivers for the soundcard. https://github.com/Audio-Injector/stereo-and-zero

In Alsamixer the card pops up and after I configured the supersid config file accordingly to work with the audioinjector soundcard,
supersid.py works as should be :-) 

Why it did not work last year, I don't know. Maybe it was my fault not following instructions fro the audioinjector github page, or is it Bullseye versus Buster last year? 

Anyway glad that it is working. I can capture on 2 channels with 192Khz with this card. Next step will be to get it to work on a pi zero.

**Comment by kunkleb** [comment]
Hi,
Glad to see that you have the pi zero working.
I have used the audioinjector stereo sound card on the pi zero and it
worked fine.  I also used the audioinjector zero card (smaller footprint)
in stereo mode capturing 2 channels on the pi zero.  That also worked fine.
I am currently using the Codec Zero
<https://www.raspberrypi.com/products/codec-zero/> card on the pi zero.  I
am using it in single channel mode using the mic input but I believe that
it could be used for 2 channels using the stereo aux in connectors.
Good luck,
Bill

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sberl** [comment]
Is there still an issue here we can do anything about, either thru code or documentation? 
If not, I think this can be closed.

**Comment by fenrog** [comment]
solved by https://github.com/sberl/supersid/pull/131

Before the fix, this test command caused the traceback with `KeyError: 'frequency_ratio'`. If an audio card did not deliver any results, the required columns in the DataFrame have not been populated. Now they are. Even though the populated result will then be dropped by `df.dropna()`, the columns remain.

test command: `python3 find_alsa_devices.py -d=null`
