### ISSUE TITLE
Could not open capture device. Please cError alsaaudio name 'alsaaudio_soundcard' is not defined

### ISSUE THREAD

**Issue by rollnrod** [sberl/supersid#85]
Thanks for the detailed instructions on issues  and I'm sorry if I missed what to do if this error occurs.
 I copied in some of the command outputs  just in case it is needed.

Here's the error when starting supersid.py
Could not open capture device. Please cError alsaaudio
name 'alsaaudio_soundcard' is not defined
Traceback (most recent call last):
  File "/home/sid/supersid/supersid/sampler.py", line 719, in __init__self.capture_device = alsaaudio_soundcard(

I can play test sounds from the usb with terminal commands. 
speaker-test -c2 -twav -l7 -D plughw:3,0
 
 In supersid config file
[Capture]
Audio = alsaaudio
Device = plughw:CARD=S3,DEV=0
Format = S24_3LE
PeriodSize = 1024
Channels = 1

Original error starting supersid.py
Could not open capture device. Please cError alsaaudio
name 'alsaaudio_soundcard' is not defined
Traceback (most recent call last):
  File "/home/sid/supersid/supersid/sampler.py", line 719, in __init__
    self.capture_device = alsaaudio_soundcard(

sid@raspberrypi:~ $ cat /proc/asound/cards
 0 [vc4hdmi0       ]: vc4-hdmi - vc4-hdmi-0
                      vc4-hdmi-0
 1 [vc4hdmi1       ]: vc4-hdmi - vc4-hdmi-1
                      vc4-hdmi-1
 2 [Headphones     ]: bcm2835_headpho - bcm2835 Headphones
                      bcm2835 Headphones
 3 [S3             ]: USB-Audio - Sound Blaster Play! 3
                      Creative Technology Ltd Sound Blaster Play! 3 at usb-0000:01:00.0-1.1, full spe

(supersid-env) sid@raspberrypi:~/supersid/supersid $ python3 -u sampler.py -s=96000 -m=alsaaudio -d="plughw:CARD=S3,DEV=0" -f=S24_3LE -p=1024 2>&1

Accessing 'plughw:CARD=S3,DEV=0' at 96000 Hz via alsaaudio format S24_3LE, channels 1...
alsaaudio device 'plughw:CARD=S3,DEV=0', sampling rate 96000, format S24_3LE, channels 1, periodsize 1024
alsaaudio 'plughw:CARD=S3,DEV=0' at 96000 Hz
 96000 <class 'numpy.int64'> read from alsaaudio 'plughw:CARD=S3,DEV=0', shape (96000, 1), format S24_3LE, channel 0, duration 1.00 sec, peak freq [16171] Hz
[0 0 0 0 0 ... -19968 -24832 -29184 -26368 -18432],
Vector sum -34562048,

**Comment by rollnrod** [comment]
It appears I was not in the python virtual environment when starting the sid program.  Currently seems to be working.  Although my signal looks strange.Have t mess with antenna
